# ===============================================
# docker-compose.prod.yml
# Production override configuration
# ===============================================

version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    environment:
      NODE_ENV: production
      CREATE_ADMIN_ON_START: ${CREATE_ADMIN_ON_START:-false}
    volumes: []  # No source code mounting in production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # No initialization scripts in production
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
    profiles:
      - postgres

  redis:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    profiles:
      - redis