# Simple docker-compose.yml for MyCure Backend Assessment
version: '3.9'

services:
  api:
    build: .
    container_name: mycure-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_PATH: /app/data/mycure.db
      JWT_SECRET: your-secret-key-change-in-production
      JWT_REFRESH_SECRET: your-refresh-secret-change-in-production
    volumes:
      - api_data:/app/data
    ports:
      - "3000:3000"

volumes:
  api_data: