# ===============================================
# docker-compose.test.yml
# Testing configuration
# ===============================================

version: '3.9'

services:
  # Test runner
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: mycure-api-test
    environment:
      NODE_ENV: test
      DATABASE_PATH: /app/data/test.db
      JWT_SECRET: test-secret-key
      JWT_REFRESH_SECRET: test-refresh-secret
      ALLOWED_ORIGINS: http://localhost:3000
      LOG_LEVEL: error
    command: ['bun', 'test']
    volumes:
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./bun.lock:/app/bun.lock:ro
      - test_data:/app/data
    networks:
      - mycure-network

  # Test database (in-memory SQLite for fast tests)
  test-db:
    image: alpine:latest
    container_name: mycure-test-db
    command: ['sh', '-c', 'echo "Test database placeholder" && sleep infinity']
    networks:
      - mycure-network

volumes:
  test_data: